version: "2"

services:
  rethinkdb-1:
    build: ../rethinkdb
    command: rethinkdb --join rethinkdb-2:29015 --join rethinkdb-3:29015 --bind all
    volumes:
      - ~/rethinkdb-1:/data

  rethinkdb-2:
    build: ../rethinkdb
    command: rethinkdb --join rethinkdb-1:29015 --join rethinkdb-3:29015 --bind all
    volumes:
      - ~/rethinkdb-2:/data

  rethinkdb-3:
    build: ../rethinkdb
    command: rethinkdb --join rethinkdb-1:29015 --join rethinkdb-2:29015 --bind all
    volumes:
      - ~/rethinkdb-3:/data

  rethinkdb-proxy:
    build: ../rethinkdb
    command: rethinkdb proxy --join rethinkdb-1:29015 --join rethinkdb-2:29015 --join rethinkdb-3:29015 --bind all
    volumes:
      - ~/rethinkdb-proxy:/data
    ports:
      - "8888:8080"
      - "28015"

  rabbitmq-api:
    build: ../rabbitmq-api
    ports:
      - "15672:15672"

  redis-api:
    build: ../redis-api
    volumes:
      - ~/redis:/data
    ports:
      - "6379:6379"

  api-server:
    build: ../api-server
    command: pm2 start pm2dev.json --no-daemon
    environment:
      NODE_ENV: development
    links:
      - rabbitmq-api:rabbitmq-api
      - redis-api:redis-api
    ports:
      - "3000:3000"
    restart: on-failure:10
    volumes:
    - ../api-server:/home/service/api-server
    - /home/service/api-server/node_modules

  api-users-read:
    build: ../api-users-read
    command: pm2 start pm2dev.json --no-daemon
    environment:
      NODE_ENV: development
    links:
      - rabbitmq-api:rabbitmq-api
    restart: on-failure:10
    volumes:
    - ../api-users-read:/home/service/api-users-read
    - /home/service/api-users-read/node_modules

  api-users-write:
    build: ../api-users-write
    command: pm2 start pm2dev.json --no-daemon
    environment:
      NODE_ENV: development
    links:
      - rabbitmq-api:rabbitmq-api
    restart: on-failure:10
    volumes:
    - ../api-users-write:/home/service/api-users-write
    - /home/service/api-users-write/node_modules

  api-authorize:
    build: ../api-authorize
    command: pm2 start pm2dev.json --no-daemon
    environment:
      NODE_ENV: development
    links:
      - rabbitmq-api:rabbitmq-api
    restart: on-failure:10
    volumes:
    - ../api-authorize:/home/service/api-authorize
    - /home/service/api-authorize/node_modules

  api-attachments-read:
    build: ../api-attachments-read
    command: pm2 start pm2dev.json --no-daemon
    environment:
      NODE_ENV: development
    links:
      - rabbitmq-api:rabbitmq-api
    restart: on-failure:10
    volumes:
    - ../api-attachments-read:/home/service/api-attachments-read
    - /home/service/api-attachments-read/node_modules

  api-attachments-write:
    build: ../api-attachments-write
    command: pm2 start pm2dev.json --no-daemon
    environment:
      NODE_ENV: development
    links:
      - rabbitmq-api:rabbitmq-api
    restart: on-failure:10
    volumes:
    - ../api-attachments-write:/home/service/api-attachments-write
    - /home/service/api-attachments-write/node_modules
